apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh", "-c", "echo hello; sleep 3600"]
  - image: busybox
    name: busybox2
    command: ["/bin/sh", "-c", "echo hello; sleep 3600"]
  restartPolicy: Never
