apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  initContainers:
    - name: copy-redis-config
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          cp /configmap/redis.conf /redis-master/redis.conf
      volumeMounts:
        - name: redis-config-map
          mountPath: /configmap
        - name: redis-config
          mountPath: /redis-master

  containers:
    - name: redis
      image: redis:7
      command: ["redis-server", "/redis-master/redis.conf"]
      ports:
        - containerPort: 6379
      volumeMounts:
        - name: redis-config
          mountPath: /redis-master
        - name: redis-data
          mountPath: /redis-data

  volumes:
    - name: redis-config
      emptyDir: {}

    - name: redis-data
      emptyDir: {}

    - name: redis-config-map
      configMap:
        name: redis-config

